import type { AdminProjectRow } from '#layers/projects/domain/projectSelect'

export function buildAdminProjectRow(overrides: Partial<AdminProjectRow> = {}): AdminProjectRow {
  return {
    id: 'project-1',
    published_at: null,
    slug_ro: 'saas-logistica',
    slug_en: 'logistics-saas',
    title_ro: 'Titlu',
    title_en: null,
    card_title_ro: 'Card',
    card_title_en: null,
    summary_ro: 'Sumar',
    summary_en: null,
    lead_ro: 'Lead',
    lead_en: null,
    year: 2025,
    tech: ['Nuxt'],
    service_tag: null,
    featured: false,
    cover_path: null,
    cover_alt_ro: null,
    cover_alt_en: null,
    hero_path: null,
    hero_alt_ro: null,
    hero_alt_en: null,
    kind_ro: null,
    kind_en: null,
    tags_ro: [],
    tags_en: [],
    live_url: null,
    live_url_label_ro: null,
    live_url_label_en: null,
    screens_demo: false,
    context_body_ro: 'Problema',
    context_body_en: null,
    solution_body_ro: null,
    solution_body_en: null,
    obstacles_body_ro: null,
    obstacles_body_en: null,
    changes_body_ro: null,
    changes_body_en: null,
    result_body_ro: null,
    result_body_en: null,
    quote_ro: null,
    quote_en: null,
    quote_author: null,
    quote_role_ro: null,
    quote_role_en: null,
    quote_company: null,
    sort_order: 0,
    project_facts: [],
    project_stack: [],
    project_stats: [],
    project_images: [],
    ...overrides,
  }
}
