DROP TABLE IF EXISTS service_items CASCADE;
DROP TABLE IF EXISTS services CASCADE;

CREATE TABLE services (
  id text PRIMARY KEY,
  "orderNumber" int NOT NULL DEFAULT 0,
  title_ro text NOT NULL,
  title_en text NOT NULL,
  pricing_ro text NOT NULL,
  pricing_en text NOT NULL,
  timing_ro text NOT NULL,
  timing_en text NOT NULL,
  "whereYouAre_ro" text NOT NULL,
  "whereYouAre_en" text NOT NULL,
  "whatYouGet_ro" text NOT NULL,
  "whatYouGet_en" text NOT NULL,
  "whyUs_ro" text,
  "whyUs_en" text,
  chips_ro jsonb NOT NULL DEFAULT '[]'::jsonb,
  chips_en jsonb NOT NULL DEFAULT '[]'::jsonb,
  cta_ro text NOT NULL,
  cta_en text NOT NULL,
  "isActive" boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Activează regulile de securitate (RLS)
ALTER TABLE services ENABLE ROW LEVEL SECURITY;
CREATE POLICY public_read_services ON services FOR SELECT USING ("isActive" = true);
CREATE POLICY admin_all_services ON services FOR ALL USING (is_admin()) WITH CHECK (is_admin());

-- Inserează serviciile
INSERT INTO services (
  id, "orderNumber", 
  title_ro, title_en, 
  pricing_ro, pricing_en, 
  timing_ro, timing_en, 
  "whereYouAre_ro", "whereYouAre_en", 
  "whatYouGet_ro", "whatYouGet_en", 
  "whyUs_ro", "whyUs_en", 
  chips_ro, chips_en, 
  cta_ro, cta_en,
  "isActive"
) VALUES
('E', 1, 
  'EXPRESS PAGE', 'EXPRESS PAGE', 
  'Sub 1.000 EUR', 'Under 1,000 EUR', 
  '2–3 zile', '2–3 days', 
  'Ai nevoie de o pagină rapidă și modernă pentru a valida o idee, a câștiga primii clienți sau a înlocui un site învechit.', 'You need a modern, fast page to validate an idea, win your first customers or replace an outdated site.', 
  'Un landing page de 1–3 pagini care se încarcă rapid, optimizat pentru mobil și conectat direct la Telegram sau formular, astfel încât cererile să ajungă la tine din prima zi.', 'A fast-loading 1–3 page landing site, mobile-optimised, wired straight to Telegram or a form so enquiries reach you from day one.', 
  'Site-urile construite în platforme de tip DIY (do-it-yourself) îți economisesc bani acum, dar te costă credibilitate. O pagină creată de profesioniști se încarcă mai rapid și chiar convertește vizitatorii în clienți.', 'DIY builders save money now but cost you credibility. A pro page loads faster and actually converts your traffic.', 
  '["Lansare în 2–3 Zile", "Design Modern", "Optimizat Mobil", "Formular Conectat"]', '["Launch in 2–3 Days", "Modern Design", "Mobile-Optimised", "Form Connected"]', 
  'Lansează pagina mea', 'Launch my page',
  true),
('B', 2, 
  'CONCEPT LA SPECIFICAȚIE', 'CONCEPT TO SPEC', 
  'De la 1.000 EUR', 'From 1,000 EUR', 
  '~1 săptămână', '~1 week', 
  'Ai o idee de produs sau afacere, dar e încă la nivel teoretic și ai nevoie de claritate completă înainte de a investi în dezvoltare.', 'You have a product or business idea, but it''s still theoretical and you need full clarity before investing in development.', 
  'Un plan complet de execuție: de la fluxuri de utilizator și un prototip vizual la o specificație tehnică clară, gata de a fi predată unei echipe de dezvoltare.', 'A complete execution plan: from user flows and a visual prototype to a clear technical spec, ready to hand to a dev team.', 
  'Sărirea peste etapa de specificație înseamnă de obicei costuri suplimentare și întârzieri mai târziu. Aliniem logica de business cu realitatea tehnică înainte de a scrie vreo linie de cod.', 'Skipping the spec phase usually means scope creep later. We align business logic with tech reality before writing any code.', 
  '["Prototipare UI/UX", "Wireframe-uri", "Definire Scop Produs"]', '["AI Prototyping", "Wireframing", "Product Scope"]', 
  'Conturează conceptul meu', 'Map out my concept',
  true),
('A', 3, 
  'DESIGN ÎN COD', 'DESIGN TO CODE', 
  'De la 2.000 EUR', 'From 2,000 EUR', 
  '3–6 săptămâni', '3–6 weeks', 
  'Design-ul este gata în Figma sau resursele vizuale sunt pregătite, și vrei o echipă tehnică care să le transforme într-un cod de producție bine scris.', 'Your design is ready in Figma, or your visual assets are prepared, and you want a technical team to turn them into well-built production code.', 
  'Ecranele din Figma transformate într-o aplicație funcțională: front-end, bază de date Postgres și integrările API necesare.', 'Your Figma screens built as a working app: front end, Postgres database and the API integrations it needs.', 
  'Agențiile offshore livrează deseori cod greu de întreținut. Noi livrăm o arhitectură curată, scalabilă, pe care o deții în totalitate.', 'Offshore agencies often produce unmaintainable code. We ship clean, typed, scalable architecture you actually own.', 
  '["Pixel-Perfect", "Arhitectură Full-Stack", "Deploy pe Vercel", "Schemă Postgres"]', '["Pixel-Perfect", "Full-Stack Architecture", "Deploy on Vercel", "Postgres Schema"]', 
  'Transformă designul în cod', 'Turn my design into code',
  true),
('C', 4, 
  'SCALARE ȘI EXTINDERE', 'SCALE & EXTEND', 
  'De la 2.000 EUR', 'From 2,000 EUR', 
  '4–8 săptămâni', '4–8 weeks', 
  'Ai un produs live, dar ai nevoie de capacitate tehnică pentru a lansa module noi, a rezolva probleme de performanță sau a crește viteza de livrare.', 'You have a live product but need engineering capacity to ship new modules, clear performance bottlenecks or increase delivery speed.', 
  'Dezvoltare de module noi, refactorizare de cod, optimizare a bazei de date și o arhitectură pregătită pentru scalare — fără întreruperi de funcționare.', 'New feature development, code refactoring, database tuning and an architecture ready to scale — with zero downtime.', 
  'În loc doar să aplicăm „plasturi” peste erori, modernizăm stiva tehnologică treptat, astfel încât să poți crește fără a arunca la gunoi codul existent.', 'Instead of just patching bugs, we modernize your stack iteratively so you can grow without throwing away existing code.', 
  '["Funcționalități Noi", "Optimizare Viteză", "Arhitectură Scalabilă", "Refactorizare Treptată"]', '["New Features", "Speed Optimisation", "Scalable Architecture", "Incremental Refactor"]', 
  'Scalează produsul meu', 'Scale my product',
  true),
('D', 5, 
  'AUTOMATIZARE PROCESE', 'AI PROCESS AUTOMATION', 
  'De la 5.000 EUR', 'From 5,000 EUR', 
  '6–12 săptămâni', '6–12 weeks', 
  'Echipa ta pierde zeci de ore cu sarcini repetitive, procesare manuală de date sau fluxuri fragmentate care încetinesc creșterea afacerii.', 'Your team loses dozens of hours on repetitive tasks, manual data processing or fragmented workflows that slow your growth.', 
  'Pași inteligenți (LLM) integrați în uneltele pe care le folosești deja (n8n, Make sau cod personalizat), plus un dashboard unde echipa aprobă sau revizuiește automatizările.', 'LLM steps wired into the tools you already use (n8n, Make or custom code), plus a dashboard where your team reviews every automated action.', 
  'Soluțiile de inteligență artificială generice sunt limitate. Construim automatizări sigure și personalizate pentru fluxul tău specific de business.', 'Off-the-shelf AI tools are generic. We build custom automations that fit your exact business process securely.', 
  '["Costuri Operaționale Reduse", "Integrări AI Custom", "Procesare Automată", "Control și Audit"]', '["Lower Operating Costs", "Custom AI Integrations", "Automated Processing", "Control & Audit"]', 
  'Automatizează fluxul', 'Automate my workflow',
  true);
